@startuml friends

!include ../styles.puml

' Таблица друзей
entity friends {
    + user_id: INT [PK, FK -> users.id]
    + friend_id: INT [PK, FK -> users.id]
    --
    created_at: TIMESTAMP [DEFAULT CURRENT_TIMESTAMP]
}

@enduml
