@startuml post_likes

!include ../styles.puml

' Таблица лайков к постам
entity post_likes {
    + post_id: INT [PK, FK -> posts.id]
    + user_id: INT [PK, FK -> users.id]
    --
    created_at: TIMESTAMP [DEFAULT CURRENT_TIMESTAMP]
}

@enduml
