@startuml user_interests

!include ../styles.puml

' Таблица интересов
entity user_interests {
    + id: SERIAL [PK]
    --
    user_id: INT [NOT NULL, FK -> users.id]
    quotes: VARCHAR(1000)
    activity: VARCHAR(500)
    favorite_music: VARCHAR(1000)
    favorite_books: VARCHAR(1000)
    favorite_games: VARCHAR(1000)
}

@enduml
