@startuml user_languages

!include ../styles.puml

' Таблица связи пользователей и языков
entity user_languages {
    + user_id: INT [PK, FK -> users.id]
    + language_id: INT [PK, FK -> languages.id]
}

@enduml
